### ISSUE TITLE
Add way to link clues.

### ISSUE THREAD

**Issue by elwoodpd** [viresh-ratnakar/exet#1]
Don't know if I am just being thick, but I can't seem to find how you would to paired up clues. E.g. answers that run over multiple numbers.

**Comment by viresh-ratnakar** [comment]
At this time, the Exet interface does not support creating linked clues (I'll get around to it eventually).

However, you can create linked clues easily by editing the Exolve file, which is a plain text format. And then you can load the modified Exolve file from Exet, and the linked clue should survive and should play well with Exet (but let me know if you see any issues).

In Exolve, you specify a linked clue as you would expect. Eg:

exolve-across:
  2 Some across clue ... (5)
  ...
  12 See 13.
  ... 
exolve-down:
  ...
  2 See 13.
  13, 12, 2d A linked clue that includes 12a (assuming there is no 12d, "12" is unambiguous), and 2d (4,5,3)

**Comment by viresh-ratnakar** [comment]
I've added support for creating/busting linked clues now, in v0.27.

From the README.md file:

#### Linked clues

You can link clues, creating sequences of lights that make up a single solution
that is clued using the "parent" clue (the first one in the sequence). To
create such linkages, you can click on the clue number of the current clue,
which will bring up a panel through which you can add a linked clue to the
current clue. The same panel also provides a button for breaking up a group
of previously linked clues. When you break up a group of linked clues, any
existing clue text from them will also get deleted.

Grid-fill suggestions as well as autofill work as you might expect with linked
clues.
