### ISSUE TITLE
[Feature Request] Saving to and loading from a cloud storage provider

### ISSUE THREAD

**Issue by Bickio** [viresh-ratnakar/exet#13]
I use this app on my phone while commuting, and on my desktop PC at home. Currently, transferring a between these two devices involves:

- Saving locally from Exet
- Uploading to a cloud storage provider (google drive, dropbox, etc.)
- Downloading to the other device
- Uploading to Exet

This process could be simplified by integrating a cloud storage provider directly into the app.

As an example of how this feature could work (using dropbox):

- On each device, Exet authenticates with dropbox (OAuth, or perhaps simple access tokens)
- Exet then uses the '/exet' folder in the user's account to store saved puzzles
- The list of saved puzzles is displayed and can be loaded directly
- An open puzzle can be saved back to dropbox (perhaps using revisions?)

I'm more than happy to help implementing this feature, if you feel it would be useful.

**Comment by viresh-ratnakar** [comment]
Hi!

First off, I'm amazed that you've been able to use Exet on the phone! I've found it quite clunky, esp, with the keyboard mostly obscuring everything. But perhaps you use some nicer/different/custom set-up. It would be great if you drop a usage note in the Discussions area about that, if there's anything noteworthy.

As to the feature request itself: I think that this is probably not core-crossword-related functionality, and also your specific use case--at least at this time--is not very common. As you might have noticed, my coding philosophy for web apps is to absolutely avoid dependencies on packages/frameworks etc. Of course, I may be a bit over-the-top in that position, but I do think that makes the project more stable over time, more easily reusable/modifiable, less brittle. So, on balance, I think that adding all this authentication and syncing code into Exet is not something I would want.

That said, I think the problem that you're facing is fundamentally a file-sharing problem, not an Exet/crossword problem. Whatever coding you intended to do, can, I am guessing, can also be done in the context of a stand-alone app/web-app that lets me sync some chosen directory (say my Chrome/Firefox/whatever Downloads folder) across devices, using Google Drive or Dropbox or whatever. *That* would be super-general and useful across many apps. Then, from your phone Exet, you save the current state by downloading a file to the Downloads folder (as is already possible), and that file magically appears in the Downloads folder of the browser on your other computer, and you can load it up in Exet from that browser.

Thanks,
Viresh

**Comment by viresh-ratnakar** [comment]
I'll close this bug in a day or so, unless there's a follow-up discussion.
