### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by elwoodpd** [viresh-ratnakar/exet#14]
I understand that for some people spellcheck is not helpful and that lots of words used in a crossword are not going to be in the system dictionary but I personally still rely pretty heavy on spellcheck for avoiding simple spelling mistakes and typos in ordinary words. I guess this might be unusual for people who set cryptic crosswords, but I genuinely find it essential. Could an option to turn it back on be added?

**Comment by viresh-ratnakar** [comment]
Sure, I'll add an option!

**Comment by viresh-ratnakar** [comment]
I've added this in v0.40 now. Here's the relevant documentation:

The text-editing panel for the current clue/anno disables spellcheck by
default. You can turn it on or off through the "Edit &rarr; Preferences:"
menu. This setting persists in Exet, across different crosswords. Note that
if you change the setting, depending on some browser peculiarities, the
updated setting may only become active after you have navigated to a new
clue and/or clicked on the clue or anno.

**Comment by viresh-ratnakar** [comment]
Closing (please reopen if you notice any issues).

**Comment by elwoodpd** [comment]
Perfect, thank you!!
