### ISSUE TITLE
Support xml export compatible with crossword compiler

### ISSUE THREAD

**Issue by elwoodpd** [viresh-ratnakar/exet#15]
My personal interest in this is not really using CCW (I prefer exet) but rather certain websites and publishers treat CCW  as the standard format. Supporting .ccw files or .xml seems like a cool possible feature. Not sure if there is an example implementation anywhere.

https://www.crossword-compiler.com/ is what I am talking about and the demo will let you import puz files and export xml or .ccw files so it shouldn't be too hard to get examples to work from.

**Comment by viresh-ratnakar** [comment]
I looked into it a bit, but I could not find any specs. This is (another) proprietary format and adding support for it will add complexity to Exet but the functionality will be imperfect and subject to go obsolete.

I am not a crossword compiler customer and hence I do not have detailed access to their site. I also do not have a Windows/Mac computer, so I cannot try their demo :-). However, if you can point me to some examples, I can perhaps code up a standalone PUZ->CCW converter (or even can try adding it to puzpy) as one way of creating CCW files from Exet.

**Comment by viresh-ratnakar** [comment]
Closing this (but am still open to writing a standalone/pyzpy-part PUZ->CCW converter, if I can find some example files).
