### ISSUE TITLE
Break up multi-word during autofill

### ISSUE THREAD

**Issue by anand-rr** [viresh-ratnakar/exet#16]
Not sure if this already happens, haven't seen it while using auto-fill. It would be cool if auto-fill tried to split a multi-word entry across multiple entries. It could increase usage of preferred-fill entries.

**Comment by viresh-ratnakar** [comment]
Interesting idea. No, it doesn't happen right now. But the workaround is to put the multi-word entry into the preferred list as separate words (of course, with some extra manual work to reject fills that only use some of the multiple words).

I'll look into it. Will do if it can be done without adding too much extra complexity to the code.

**Comment by viresh-ratnakar** [comment]
I haven't done this yet. Am probably not likely to, as it would add complexity and the use-case is fairly niche. Closing this issue with apologies.

I did improve auto-fill a bit recently (v0.75). This includes better coverage of preferred fills and showing which preferred fills have been used.
