### ISSUE TITLE
unsymmetrical crossword possible?

### ISSUE THREAD

**Issue by RobertEcker** [viresh-ratnakar/exet#17]
Hi ;)

Is it possible to create asymmetrical crosswords too?
If yes, how?

**Comment by viresh-ratnakar** [comment]
Hi, yes, this is already possible. It is slighlty painful, I'll admit (but it's done this way as a design choice, to keep the more common case -- that of symmetry -- simple to maintain).

You should start with a completely blank grid. Or you can start with a new symmetric grid with blocks -- what you get on a new grid with the "Add automagic blocks" option turned on.

You can then modify this starting point by adding blocks (and/or bars), *while forcing the option to not enforce symmetry* on each added block.

On the Exet tab, in the Edit menu, go to the "Edit grid cell:" sub-menu. At the top, there is a checkbox option that says: "Do not force symmetry on the next 'Toggle block/bar'" -- check that option and then add a block in any cell (using the menu or by pressing "." in that cell). A symmetric block will *not* get placed. Repeat the procedure (but you'll have to check the toggle option for every added block that you do not want a symmetric counterpart for -- that's the painful part).

**Comment by viresh-ratnakar** [comment]
Closing this now, hopefully the answer is good enough.

**Comment by martindemello** [comment]
why not have the setting be global and sticky until toggled back?

**Comment by viresh-ratnakar** [comment]
I can do that. I worry a bit about "forgetting to toggle it back on," but I suppose I can address that with a "tip" showing up if symmetry is off and you try to add a new block.

**Comment by martindemello** [comment]
or change the grid border colour to red if symmetry is off :)

**Comment by viresh-ratnakar** [comment]
Oh, the setting *is* sticky currently, but just for the current crossword. I thought I had it apply only to the next added block/bar, but that's not the case. So, I think that is how it should be—it should *not* persist on to a new crossword.

Or am I missing something?

I *am* going to move the setting from "Edit > Edit grid cell > [checkbox]" to "Edit > Preferences > [checkbox]." I will also play a bit with the idea of a visual indicator for this setting.

**Comment by viresh-ratnakar** [comment]
Closing again, as no further change seems to be really needed.
