### ISSUE TITLE
Use Exolve and Exet in GitHub Desktop

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exet#20]
I may be being dumb here, but I can keep both apps up to date using GitHub Desktop but it seems I need to have all the html files for both in one folder for exet to work, otherwise it throws an error that it can't define exolve.
Could the define exolve step maybe check for the exolve files in a sibling folder if they aren't in the same folder?

**Comment by viresh-ratnakar** [comment]
Closing, but feel free to reopen.
