### ISSUE TITLE
Typed clues lost if focus is changed too fast.

### ISSUE THREAD

**Issue by elwoodpd** [viresh-ratnakar/exet#21]
I don't know if this has always been the case, but when you click away from editing a clue too soon, everything you typed is lost.

Steps to reproduce: type a clue. When you finish typing press tab. When you go back to the clue it will be replaced with the default message about drafts.

**Comment by viresh-ratnakar** [comment]
I've fixed this now, with v0.69.

**Comment by viresh-ratnakar** [comment]
Closing; please reopen if something related recurs.
