### ISSUE TITLE
Which preferred fills have been used

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exet#26]
I might be being dumb, but when I autofill, I see how many of my preferred fills have been used but not which. If I have 100 preferred fills, that's quite hard to work out manually. If the feature doesn't exist already, wouldn't it make sense to highlight the preferred fills that are in the grid?
Amazing app tho Viresh, hats off to you

**Comment by viresh-ratnakar** [comment]
That feature does not exist right now, and it makes sense to add it, sure. Will add soon!

**Comment by viresh-ratnakar** [comment]
This is done now, with v0.75.

**Comment by ballantynedewolf** [comment]
Amazing


Jonathan Sykes
+61404719997
