### ISSUE TITLE
Preamble editing window narrower than line length with no horizontal scroll bar

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exet#27]
I'm using Edge on Win10, all latest.
![image](https://user-images.githubusercontent.com/25334785/215248169-dc985a88-a777-4288-8717-9f7a0ef03c2b.png)

**Comment by viresh-ratnakar** [comment]
Addressed with v0.78.1 with the following changes as listed in the CHANGELOG.md file:

- Reduce textarea cols for Preamble/Explanations/Other Sections editables
  to 55 from 80. Also make horizontal scrollbars appear too, when needed.

**Comment by viresh-ratnakar** [comment]
Hopefully the issue has been resolved for you. Will close the bug shortly.
