### ISSUE TITLE
allow toggling of bars by clicking on an edge

### ISSUE THREAD

**Issue by martindemello** [viresh-ratnakar/exet#29]
not sure how hard this is to implement in a browser but it would be very convenient to be able to set bars using just the mouse

**Comment by viresh-ratnakar** [comment]
Hmm, this one I'm inclined to push back on. The clickable area will be small, so it will require painful precision. Accidental clicks can happen (as one can click on a square just to go to that square) and spoil the grid. The added code complexity does not seem worth it to me.

There are keyboard shortcuts--I've used them to set a couple of barred grids in the past, and got used to them quickly enough. There's also a menu, but that's obviously more painful.

Feel free to counter and press on, we'll see :-)

**Comment by martindemello** [comment]
yeah, the keyboard shortcuts worked well enough but i got used to clicking on bars in qxw :) fair point about the accidental clicks though.
