### ISSUE TITLE
What's the best way for two people to collaborate remotely on and exet project?

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exet#31]
Title says it all really. Cheers, Jona

**Comment by viresh-ratnakar** [comment]
There's no built-in support, and it's unlikely that I'll work on it anytime soon, at least not in the sense of building and maintaining a server that Exet instances can talk to. That's something I've thought about doing for Exolve (collaborative solving), which seems to be a higher priority to me, but again, the complexity of maintaining a running service seems too much to me.

Now, all that said, here are some workarounds:
- Use Zoom / Google Meet and screen-share :-).
- One person acts as the primary. Both parties maintain a copy of the puzzle. They discuss changes over email/whatever, exchange their latest saved Exolve files ("Save -> Download Exolve file with solutions"). The primary party is responsible for assimilating changes from the secondary party and sending over the updated version. This is what I have done with a couple of collaborations, myself.
- The primary party can use a diff tool (I use vimdiff) to help with the above. Say, the secondary party saves their puzzle and sends over `secondary-file.html`. The primary party would save too, to get `primary-file.html`, then would use the diff tool to assimilate changes, and then load the merged file (`merged-file.html`) into Exet. This would just extend the existing puzzle's revision history, it would _not_ create an all new puzzle (as they carry the same "exolve-id").

**Comment by ballantynedewolf** [comment]
Thanks mate
