### ISSUE TITLE
Search nutrimatic / onelook / ??? for fill

### ISSUE THREAD

**Issue by mooomooo** [viresh-ratnakar/exet#32]
In place of / to supplement a custom lexicon (#3), it might be nice to have the ability to directly search nutrimatic / onelook for fill that match the currently filled in length and crossers.  Perhaps a button to append the search results to the list from the lexicon, or a separate tab in the word list, or just additional entries in the "research" tab?

Thanks for this amazing tool!

**Comment by viresh-ratnakar** [comment]
Thanks! Yes, that's a very good idea. Think aloud a bit about the details (inputs from anyone are welcome): Nutrimatic results in general will be low-precision/high-recall (as many/most of the phrase matches will not be usable), so I wouldn't want to just mix them into the lexicon matches. I think additional entries in the "Research" tab seems like the easiest thing to do as well as the right way to do it.

**Comment by viresh-ratnakar** [comment]
BTW: there are many times when it would be nice to get weigh-ins from more users, and I find that rarely happening on GitHub Issue/Discussion area. So I've now created a Google Group. Do consider joining: https://groups.google.com/g/exolve-exet-etc

**Comment by mooomooo** [comment]
(Github is easier for me than Google Groups) From the group: 

> I am thinking of removing the "Clear light" button that is currently shown in the Exet tab, above the grid-fill choices. I will add it to the Edit menu. The keyboard short-cut (Ctrl-q) will continue to work. I am thinking of using that space to offer a choice of fetching grid-fill matches from sources such as Nutrimatic and Onelook (to supplement what you get from the lexicon: see https://github.com/viresh-ratnakar/exet/issues/32).

I think this sounds like a better idea actually, though probably more work -- it makes more sense for the words to show up in this tab than under "Research".  I do see your point about not mixing results though, so maybe the word list choices box could be made to have separate tabs for lexicon / nutrimatic / onelook matches?

**Comment by viresh-ratnakar** [comment]
On Tue, Jun 4, 2024 at 4:21 PM mooomooo ***@***.***> wrote:

> (Github is easier for me than Google Groups) From the group:
>
> I am thinking of removing the "Clear light" button that is currently shown
> in the Exet tab, above the grid-fill choices. I will add it to the Edit
> menu. The keyboard short-cut (Ctrl-q) will continue to work. I am thinking
> of using that space to offer a choice of fetching grid-fill matches from
> sources such as Nutrimatic and Onelook (to supplement what you get from the
> lexicon: see #32 <https://github.com/viresh-ratnakar/exet/issues/32>).
>
> I think this sounds like a better idea actually, though probably more work
> -- it makes more sense for the words to show up in this tab than under
> "Research". I do see your point about not mixing results though, so maybe
> the word list choices box could be made to have separate tabs for lexicon /
> nutrimatic / onelook matches?
>
Yes, this is exactly what I was thinking: a drop-down, defaulting to
Lexicon.

**Comment by viresh-ratnakar** [comment]
Ah, I just realized (I have had the same realization many times :-)), that I can't really access the data returned by nutrimatic, from within Exet (as it's cross-domain data). So, I cannot mix the results into the lexicon results anyway. Moreover, I can't enable click-to-select on those nutrumatic results. At best, I can show them in an iframe (just like I do for Hidden/Alternations).

It probably still makes sense to initiate the action of getting fill choices from other sources from the main Exet tab itself, probably a button called "Web sources" that replaces the "Clear light" button. I'll make a modal iframe appear, in which you can see nutrimatic and onelook results.

**Comment by viresh-ratnakar** [comment]
This has been implemented now in Exet v0.92.

https://github.com/viresh-ratnakar/exet/commit/0a7ad245fa8e91ff5b72ca2e5704e26febb88ce5

**Comment by mooomooo** [comment]
I tried it out; it looks and works great!  Thanks for this!
