### ISSUE TITLE
preferred fills seem to always give `Update failed in makeExolve()! Best to reload.`

### ISSUE THREAD

**Issue by bobular** [viresh-ratnakar/exet#34]
Hi there,

I made a 21x21 grid and pasted in 83 preferred words.

It seems that whenever I add a preferred answer to the grid, I get `Update failed in makeExolve()! Best to reload.`  after some time thinking and my browser (Firefox) asking if I want to stop the JavaScript that is "slowing my browser down".

Is it a problem with the larger grid size?

Seems to be only for preferred words that aren't in the "dictionary"?

**Comment by viresh-ratnakar** [comment]
Hi, 83 seems like a lot! But I would like to take a look at it. There are (at least :-)) three possibilities:

- It's a bug (perhaps related to non-dict words, as you're guessing)
- It's a limitation of the current algorithms
- Your word lists + grid are simply un-fillable

The first case will be the easiest to deal with.

Can you please send me your precise fill choices and grid design. If you prefer to keep them out of the public bug, feel free to email me directly at viresh at gmail dot com. For the grid, you can send me a text representation or you can mail me a .puz or exolve file.

**Comment by bobular** [comment]
Thank you for your quick reply. I did some more diagnosis and found that
1. Grid size is not an issue. Can reproduce with 15x15
2. Preferred fills list size is not an issue, can reproduce with size=1
3. The problem only occurs if the word is not already known to your algorithm. Try "coldplay"!

**Comment by bobular** [comment]
Oh, and one quick user question... Is there an "undo" shortcut to remove the word you just put in?

**Comment by viresh-ratnakar** [comment]
Thanks! I did find a bug that had crept in when I added stemmed-deduplication recently, and it did manifest for words not present in the lexicon. I've fixed that bug now, so PTAL, perhaps that was the whole issue.

There is no "undo" shortcut currently (you have to "Open > Go back to a specific revision of the current puzzle > ...").

However, there *is* a shortcut for erasing the current entry: Ctrl-q. This may be all you need?
