### ISSUE TITLE
Support non-symmetric grids

### ISSUE THREAD

**Issue by Julian-O** [viresh-ratnakar/exet#8]
It is generally a very useful feature that when you enter a block or a bar, it enforces 180 degree symmetry.

However, some crosswords (no matter how much we frown on it!) do not have 180 degree symmetry, and I believe such puzzles cannot be entered with this tool.

Please allow the automated symmetry to be turned off.

**Comment by viresh-ratnakar** [comment]
I've added this feature in v0.26, ptal: you can turn off symmetry enforcement temporarily from the Edit menu, just for the next "Toggle block/bar" operation. While this may be a little inconvenient if every single added block/bar is going to need to be asymmetric, but I'd rather not make the setting sticky, hopefully discouraging extremely asymmetric grids.
